CREATE TABLE TOKENS(
    ID INT NOT NULL AUTO_INCREMENT,
    BENUTZER INT NOT NULL,
    ANGEMELDET DATETIME DEFAULT CURRENT_TIMESTAMP,
    LETZTEAKTION DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOKEN VARCHAR(40) NOT NULL,
    MITTEILUNG INT DEFAULT 0,
    PRIMARY KEY(ID)
);
