CREATE TABLE KUNDEN(
    ID INT NOT NULL AUTO_INCREMENT,
    BENUTZER INT DEFAULT 0,
    NAME VARCHAR(100) NOT NULL,
    ADDRESSE VARCHAR(150) NOT NULL,
    TELEFON VARCHAR(20) NOT NULL,
    IDNR VARCHAR(11) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(BENUTZER) REFERENCES BENUTZER(ID)
);
