CREATE TABLE MITTEILUNGEN(
    ID INT NOT NULL AUTO_INCREMENT,
    VORNAME VARCHAR(50) NOT NULL,
    NACHNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEFON VARCHAR(15) NOT NULL,
    MITTEILUNG VARCHAR(250) NOT NULL,
    ZEIT DATETIME DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY(ID)
);