CREATE TABLE ABONNEMENT(
    ID INT NOT NULL AUTO_INCREMENT,
    BENUTZER INT DEFAULT 0,
    AUS DATETIME DEFAULT CURRENT_TIMESTAMP, 
    BIS DATETIME DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY(ID),
    FOREIGN KEY(BENUTZER) REFERENCES BENUTZER(ID)
);
