CREATE TABLE NACHRICHTEN(
    ID INT NOT NULL AUTO_INCREMENT,
    THEMA VARCHAR(50) NOT NULL,
    DATUM DATETIME DEFAULT CURRENT_TIMESTAMP, 
    AUTOR INT DEFAULT 0,
    INHALT TEXT,
    PRIMARY KEY(ID)
);