CREATE TABLE BENUTZER(
    ID INT NOT NULL AUTO_INCREMENT,
    BENUTZERNAME CHAR(64) NOT NULL,
    PASSWORT CHAR(64) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PRIVILEGIEN INT DEFAULT 0,
    BZONE INT DEFAULT 0,
    PRIMARY KEY(ID)
);
